/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/../assets/images/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/components/SlideItem` | `/components/SlideItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/components/PaginationDots` | `/components/PaginationDots`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/../assets/images/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/components/SlideItem` | `/components/SlideItem`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/components/PaginationDots` | `/components/PaginationDots`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/../assets/images/index${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/components/SlideItem${`?${string}` | `#${string}` | ''}` | `/components/SlideItem${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/components/PaginationDots${`?${string}` | `#${string}` | ''}` | `/components/PaginationDots${`?${string}` | `#${string}` | ''}` | `/../constants/Onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/../assets/images/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/components/SlideItem` | `/components/SlideItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/components/PaginationDots` | `/components/PaginationDots`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
