name: Main Branch Unit Testing # Workflow name (first part of the check label)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Unit Tests (${{ github.ref_name }}) # Job name (second part of the check label)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "❌ package-lock.json is missing."
            echo "Run 'npm install' locally and commit the generated package-lock.json."
            exit 1
          fi

      - name: Verify package-lock.json is in sync
        run: |
          cp package-lock.json package-lock.json.bak
          npm install --package-lock-only --ignore-scripts
          if ! diff -q package-lock.json package-lock.json.bak > /dev/null; then
            echo "❌ package-lock.json is out of sync with package.json."
            echo "Run 'rm -rf node_modules package-lock.json && npm install' locally, then commit the updated lockfile."
            exit 1
          fi
          mv package-lock.json.bak package-lock.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=text-summary --coverageReporters=json-summary --coverageReporters=lcov

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report

      - name: Post coverage summary to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage/coverage-summary.json
